@baseUrl = http://localhost:3333
@token = {{login.response.body.token}}




### Health Check
GET {{baseUrl}}/health

### Login (salva token automaticamente)
# @name login
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "password"
}

### Listar Produtos (usa token do login)
GET {{baseUrl}}/products
Authorization: Bearer {{token}}

### Fazer Compra
POST {{baseUrl}}/purchases
Content-Type: application/json

{
  "client_document": "12345678900",
  "client_name": "João Silva",
  "products": [
    {
      "product_id": 1,
      "quantity": 2
    }
  ]
}

### Listar Transações
GET {{baseUrl}}/transactions
Authorization: Bearer {{token}}